elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch
  volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
    - ${ELASTICSEARCH_INDICES_PATH}/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  links:
    - elasticsearchloadbalancer

elasticsearchloadbalancer:
  image: elasticsearch:latest
  command: elasticsearch
  volumes:
    - ./elasticsearchloadbalancer/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./elasticsearchloadbalancer/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
  ports:
    - "9201:9200"
    - "9301:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/ --auto-reload
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /pai-logs:/pai-logs
    - ./logstash/elasticsearch-template.json:/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/elasticsearch-template.json
  links:
    - elasticsearchloadbalancer

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearchloadbalancer
