elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch
  volumes:
    - ./elasticsearch/config:/usr/share/elasticsearch/config
  ports:
    - "9200:9200"
    - "9300:9300"
  links:
    - elasticsearchloadbalancer

elasticsearchloadbalancer:
  image: elasticsearch:latest
  command: elasticsearch
  volumes:
    - ./elasticsearchloadbalancer/config:/usr/share/elasticsearch/config
  ports:
    - "9201:9200"
    - "9301:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /pai-logs:/pai-logs
  ports:
    - "5000:5000"
  links:
    - elasticsearchloadbalancer

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearchloadbalancer
