network.host: 0.0.0.0
cluster.name: elasticsearch-pai
network.publish_host: docker host ip address or hostname, e.g. 192.168.1.57
node.master: false 
node.data: false 
transport.publish_port: 9301 
http.publish_port: 9201 
discovery.zen.ping.multicast.enabled: false 
discovery.zen.ping.unicast.hosts: comma-separated, double-quoted host or ip address list, ports optional, docker host first, surrounded by square brackets, e.g. ["192.168.1.57", "192.168.1.77", "192.168.1.77:9301"]
